package io.github.moddpbridge.converter

import io.github.moddpbridge.model.ContentDisposition
import io.github.moddpbridge.model.ContentKind
import io.github.moddpbridge.model.ContentResult
import io.github.moddpbridge.model.Diagnostic
import io.github.moddpbridge.model.SourceLocation

/** Whether prepared HJSON still names the source Mod namespace or already uses the `dp` namespace. */
enum class RuntimePreparedOutputNamespace {
    SOURCE,
    TARGET,
}

/**
 * One inert file selected or generated by the runtime-to-DP mapper.
 *
 * When [bytes] is null, [sourcePaths] must contain exactly one release-JAR entry and the converter
 * copies its bytes from the safely-read JAR. This is the preferred form for sprites, audio and
 * bundles because it keeps the release artifact authoritative. Non-null [bytes] are mapper output,
 * normally generated HJSON below `content/`.
 */
data class RuntimePreparedFile(
    val outputPath: String,
    val sourcePaths: List<String>,
    val bytes: ByteArray? = null,
    val namespace: RuntimePreparedOutputNamespace = RuntimePreparedOutputNamespace.SOURCE,
    val reason: String = "Prepared from the source Mod's observed runtime state.",
)

/** Final file-level disposition for one real entry in the release JAR. */
data class RuntimePreparedFileResult(
    val sourcePath: String,
    val status: ConvertedFileStatus,
    val reason: String,
    val outputPaths: List<String> = emptyList(),
    val diagnosticCodes: List<String> = emptyList(),
)

/** Declaration-level result produced by the runtime mapper before common planning and packaging. */
data class RuntimePreparedContentResult(
    val sourceSymbol: String,
    val kind: ContentKind? = null,
    val disposition: ContentDisposition,
    val sourceType: String? = null,
    val targetType: String? = null,
    val outputName: String? = null,
    val outputPath: String? = null,
    val reason: String? = null,
    val diagnosticCodes: List<String> = emptyList(),
    val location: SourceLocation? = null,
) {
    internal fun toModel(): ContentResult = ContentResult(
        sourceSymbol = sourceSymbol,
        kind = kind,
        disposition = disposition,
        sourceType = sourceType,
        targetType = targetType,
        outputName = outputName,
        outputPath = outputPath,
        reason = reason,
        diagnosticCodes = diagnosticCodes,
        location = location,
    )
}

/**
 * Inert handoff from a runtime mapper to [BridgeConverter]. Constructing this value never loads or
 * executes Mod classes.
 *
 * [files] is authoritative for sprites, sounds, music and bundles: ordinary assets in the JAR that
 * are not selected here are excluded. Existing `patches/` entries are always retained. When
 * [replaceOriginalContent] is true, declarative `content/` entries are reported as replaced instead
 * of being emitted beside the runtime-derived declarations.
 */
data class RuntimePreparedConversion(
    val files: List<RuntimePreparedFile>,
    val fileResults: List<RuntimePreparedFileResult> = emptyList(),
    val contentResults: List<RuntimePreparedContentResult> = emptyList(),
    val diagnostics: List<Diagnostic> = emptyList(),
    val logs: List<String> = emptyList(),
    val metadata: Map<String, String> = emptyMap(),
    val replaceOriginalContent: Boolean = true,
)
