package io.github.moddpbridge.converter

import io.github.moddpbridge.model.ContentResult
import io.github.moddpbridge.model.ContentDisposition
import io.github.moddpbridge.model.Diagnostic
import io.github.moddpbridge.model.DiagnosticSeverity
import io.github.moddpbridge.model.SourceLocation
import io.github.moddpbridge.model.ValidationStage
import java.nio.charset.Charset
import java.nio.charset.StandardCharsets
import java.util.ServiceLoader

/** Read-only source entry supplied to a static exporter after archive security checks have passed. */
data class StaticSourceFile(
    val path: String,
    val bytes: ByteArray,
) {
    fun text(charset: Charset = StandardCharsets.UTF_8): String = bytes.toString(charset)
}

/** Stable, filesystem-independent view of one safely scanned input. */
data class StaticExportContext(
    val detectedKind: DetectedSourceKind,
    val sourceName: String,
    val slug: String,
    val modNamespace: String?,
    val files: List<StaticSourceFile>,
)

/** Whether generated HJSON still uses the source mod namespace or already targets `dp-*`. */
enum class StaticOutputNamespace {
    SOURCE,
    TARGET,
}

/** One target data-asset file emitted without executing source code. */
data class StaticGeneratedFile(
    /** Target-relative path such as `content/blocks/example.hjson`. */
    val outputPath: String,
    val bytes: ByteArray,
    /** One or more original files responsible for this output. */
    val sourcePaths: List<String>,
    val namespace: StaticOutputNamespace = StaticOutputNamespace.SOURCE,
    val reason: String = "Generated by deterministic static source analysis.",
)

/** File-level outcome used to replace the normal `unsupported Java source` result. */
data class StaticSourceOutcome(
    val sourcePath: String,
    val status: ConvertedFileStatus,
    val reason: String,
    val outputPaths: List<String> = emptyList(),
    val diagnosticCodes: List<String> = emptyList(),
)

data class StaticExportResult(
    val generatedFiles: List<StaticGeneratedFile> = emptyList(),
    val sourceOutcomes: List<StaticSourceOutcome> = emptyList(),
    val contentResults: List<ContentResult> = emptyList(),
    val diagnostics: List<Diagnostic> = emptyList(),
    val logs: List<String> = emptyList(),
    val metadata: Map<String, String> = emptyMap(),
)

/**
 * SPI for deterministic code-to-data exporters. Implementations must parse only the supplied
 * bytes and must never compile, load or execute classes from the input mod.
 */
interface StaticSourceExporter {
    val id: String
        get() = javaClass.name

    fun export(context: StaticExportContext): StaticExportResult
}

/** ServiceLoader entry point used by the CLI once an exporter implementation is on its runtime classpath. */
object StaticSourceExporters {
    fun discover(
        classLoader: ClassLoader = defaultClassLoader(),
        onFailure: (Throwable) -> Unit = { throw it },
    ): List<StaticSourceExporter> {
        val exporters = mutableListOf<StaticSourceExporter>()
        val iterator = ServiceLoader.load(StaticSourceExporter::class.java, classLoader).iterator()
        while (true) {
            val hasNext = try {
                iterator.hasNext()
            } catch (error: Throwable) {
                onFailure(error)
                false
            }
            if (!hasNext) break
            try {
                exporters += iterator.next()
            } catch (error: Throwable) {
                // ServiceLoader advances past a provider name before instantiation, so later valid
                // providers can still be discovered after a missing/broken implementation.
                onFailure(error)
            }
        }
        return exporters.sortedBy { it.id }
    }

    private fun defaultClassLoader(): ClassLoader =
        Thread.currentThread().contextClassLoader ?: StaticSourceExporter::class.java.classLoader
}

internal data class StaticExportAggregate(
    val generatedFiles: List<StaticGeneratedFile> = emptyList(),
    val sourceOutcomes: Map<String, StaticSourceOutcome> = emptyMap(),
    val contentResults: List<ContentResult> = emptyList(),
    val metadata: Map<String, String> = emptyMap(),
) {
    companion object {
        val EMPTY = StaticExportAggregate()
    }
}

internal fun runStaticExporters(
    exporters: List<StaticSourceExporter>,
    snapshot: SourceSnapshot,
    detection: SourceDetection,
    diagnostics: MutableList<Diagnostic>,
    logger: ConverterLogger,
): StaticExportAggregate {
    if (exporters.isEmpty()) return StaticExportAggregate.EMPTY

    val generated = mutableListOf<StaticGeneratedFile>()
    val outcomes = linkedMapOf<String, StaticSourceOutcome>()
    val contentResults = mutableListOf<ContentResult>()
    val metadata = linkedMapOf<String, String>()
    val seenIds = hashSetOf<String>()

    exporters.sortedBy { it.id }.forEach { exporter ->
        if (!seenIds.add(exporter.id)) {
            diagnostics += Diagnostic(
                code = "STATIC_EXPORTER_ID_COLLISION",
                severity = DiagnosticSeverity.ERROR,
                message = "Multiple static exporters declared the same id '${exporter.id}'.",
                stage = ValidationStage.STRUCTURE,
            )
            return@forEach
        }
        logger.log("Running static source exporter: ${exporter.id}")
        // Each provider receives its own byte arrays so a buggy provider cannot mutate the safe
        // source snapshot or influence another provider/planning stage.
        val context = StaticExportContext(
            detectedKind = detection.kind,
            sourceName = snapshot.originalName,
            slug = detection.slug,
            modNamespace = detection.modNamespace,
            files = snapshot.entries.map { StaticSourceFile(it.path, it.bytes.copyOf()) },
        )
        val result = try {
            exporter.export(context)
        } catch (error: Throwable) {
            diagnostics += Diagnostic(
                code = "STATIC_EXPORTER_FAILED",
                severity = DiagnosticSeverity.ERROR,
                message = "Static source exporter '${exporter.id}' failed; ordinary assets will still be converted.",
                stage = ValidationStage.STRUCTURE,
                details = "${error.javaClass.name}: ${error.message.orEmpty()}",
                suggestion = "Review the exporter error and manually port declarations that were not emitted.",
            )
            logger.log("Static source exporter ${exporter.id} failed: ${error.message ?: error.javaClass.simpleName}")
            return@forEach
        }

        diagnostics += result.diagnostics
        result.logs.forEach { logger.log("[${exporter.id}] $it") }
        addMissingOutcomeDiagnostics(exporter.id, result, diagnostics)
        validateStaticExportContract(exporter.id, result, diagnostics)
        generated += result.generatedFiles.map { file ->
            file.copy(
                bytes = file.bytes.copyOf(),
                sourcePaths = file.sourcePaths.distinct().sorted(),
            )
        }
        contentResults += result.contentResults
        result.metadata.toSortedMap().forEach { (key, value) ->
            metadata["staticExporter.${exporter.id}.$key"] = value
        }
        result.sourceOutcomes.forEach { outcome ->
            val sourceExists = snapshot.entries.any { it.path == outcome.sourcePath }
            if (!sourceExists) {
                diagnostics += Diagnostic(
                    code = "STATIC_EXPORT_UNKNOWN_SOURCE",
                    severity = DiagnosticSeverity.ERROR,
                    message = "Static exporter '${exporter.id}' reported an outcome for an unknown source file.",
                    stage = ValidationStage.STRUCTURE,
                    location = SourceLocation(outcome.sourcePath),
                )
                return@forEach
            }
            val previous = outcomes.putIfAbsent(outcome.sourcePath, outcome)
            if (previous != null) {
                diagnostics += Diagnostic(
                    code = "STATIC_EXPORT_SOURCE_CONFLICT",
                    severity = DiagnosticSeverity.ERROR,
                    message = "More than one static exporter claimed the same source file.",
                    stage = ValidationStage.STRUCTURE,
                    location = SourceLocation(outcome.sourcePath),
                    details = "Kept the first deterministic outcome; conflicting exporter: ${exporter.id}",
                )
            }
        }
        logger.log(
            "Static exporter ${exporter.id} emitted ${result.generatedFiles.size} file(s), " +
                "${result.contentResults.size} content result(s), and claimed ${result.sourceOutcomes.size} source file(s).",
        )
    }

    return StaticExportAggregate(
        generatedFiles = generated,
        sourceOutcomes = outcomes,
        contentResults = contentResults,
        metadata = metadata + mapOf(
            "staticExport.generatedFiles" to generated.size.toString(),
            "staticExport.claimedSourceFiles" to outcomes.size.toString(),
            "staticExport.contentResults" to contentResults.size.toString(),
        ),
    )
}

/** Ensures every diagnostic code linked from an outcome resolves to a canonical report entry. */
private fun addMissingOutcomeDiagnostics(
    exporterId: String,
    result: StaticExportResult,
    diagnostics: MutableList<Diagnostic>,
) {
    val suppliedCodes = result.diagnostics.map { it.code }.toSet()
    result.contentResults
        .flatMap { content -> content.diagnosticCodes.map { code -> code to content } }
        .filterNot { (code, _) -> code in suppliedCodes }
        .groupBy({ it.first }, { it.second })
        .toSortedMap()
        .forEach { (code, contents) ->
            val severity = when {
                contents.any { it.disposition == ContentDisposition.FAILED || it.disposition == ContentDisposition.UNSUPPORTED } ->
                    DiagnosticSeverity.ERROR
                contents.any { it.disposition == ContentDisposition.DEGRADED } -> DiagnosticSeverity.WARNING
                else -> DiagnosticSeverity.INFO
            }
            diagnostics += Diagnostic(
                code = code,
                severity = severity,
                message = "Static exporter '$exporterId' linked declaration-level outcomes to this diagnostic code.",
                stage = ValidationStage.STRUCTURE,
                details = contents.take(20).joinToString { content ->
                    content.location?.let { "${it.path}:${it.line ?: "?"} ${content.sourceSymbol}" }
                        ?: content.sourceSymbol
                } + if (contents.size > 20) " ... (${contents.size} total)" else "",
                suggestion = "Review the matching contentResults entries for exact omissions and fallback decisions.",
            )
        }

    val knownCodes = suppliedCodes + diagnostics.map { it.code }
    result.sourceOutcomes
        .flatMap { outcome -> outcome.diagnosticCodes.map { code -> code to outcome } }
        .filterNot { (code, _) -> code in knownCodes }
        .groupBy({ it.first }, { it.second })
        .toSortedMap()
        .forEach { (code, outcomes) ->
            val severity = when {
                outcomes.any { it.status == ConvertedFileStatus.FAILED } -> DiagnosticSeverity.ERROR
                outcomes.any { it.status == ConvertedFileStatus.UNSUPPORTED } -> DiagnosticSeverity.WARNING
                else -> DiagnosticSeverity.INFO
            }
            diagnostics += Diagnostic(
                code = code,
                severity = severity,
                message = "Static exporter '$exporterId' linked file-level outcomes to this diagnostic code.",
                stage = ValidationStage.STRUCTURE,
                details = outcomes.take(20).joinToString { it.sourcePath } +
                    if (outcomes.size > 20) " ... (${outcomes.size} total)" else "",
            )
        }
}

private fun validateStaticExportContract(
    exporterId: String,
    result: StaticExportResult,
    diagnostics: MutableList<Diagnostic>,
) {
    fun normalized(path: String): String = path.replace('\\', '/').trim('/')

    val generatedPaths = result.generatedFiles.map { normalized(it.outputPath) }.toSet()
    val outcomesBySource = result.sourceOutcomes.associateBy { it.sourcePath }
    result.generatedFiles.forEach { generated ->
        generated.sourcePaths.forEach { sourcePath ->
            val outcome = outcomesBySource[sourcePath]
            if (outcome == null) {
                diagnostics += Diagnostic(
                    code = "STATIC_EXPORT_SOURCE_OUTCOME_MISSING",
                    severity = DiagnosticSeverity.ERROR,
                    message = "A generated file has no file-level static export outcome for one of its sources.",
                    stage = ValidationStage.STRUCTURE,
                    location = SourceLocation(sourcePath),
                    details = "${exporterId}: ${generated.outputPath}",
                    suggestion = "The exporter must report one StaticSourceOutcome for every claimed source file.",
                )
            } else if (normalized(generated.outputPath) !in outcome.outputPaths.map(::normalized)) {
                diagnostics += Diagnostic(
                    code = "STATIC_EXPORT_SOURCE_OUTPUT_UNLINKED",
                    severity = DiagnosticSeverity.ERROR,
                    message = "A generated file is not listed in its source file's outputPaths result.",
                    stage = ValidationStage.STRUCTURE,
                    location = SourceLocation(sourcePath),
                    details = "${exporterId}: ${generated.outputPath}",
                    suggestion = "List every generated artifact so the file-level report remains complete.",
                )
            }
        }
    }
    result.sourceOutcomes.forEach { outcome ->
        outcome.outputPaths.map(::normalized).filterNot(generatedPaths::contains).forEach { outputPath ->
            diagnostics += Diagnostic(
                code = "STATIC_EXPORT_OUTPUT_MISSING",
                severity = DiagnosticSeverity.ERROR,
                message = "A static source outcome references an output file that was not emitted.",
                stage = ValidationStage.STRUCTURE,
                location = SourceLocation(outcome.sourcePath),
                details = "${exporterId}: $outputPath",
            )
        }
    }

    val contentOutputPaths = result.contentResults.mapNotNull { it.outputPath?.let(::normalized) }.toSet()
    result.generatedFiles.asSequence()
        .map { normalized(it.outputPath) }
        .filter { it.startsWith("content/", ignoreCase = true) }
        .filterNot(contentOutputPaths::contains)
        .forEach { outputPath ->
            diagnostics += Diagnostic(
                code = "STATIC_EXPORT_CONTENT_RESULT_MISSING",
                severity = DiagnosticSeverity.ERROR,
                message = "Generated content is missing its declaration-level report result.",
                stage = ValidationStage.STRUCTURE,
                details = "${exporterId}: $outputPath",
                suggestion = "Emit a ContentResult so converted and degraded declarations remain auditable.",
            )
        }
    result.contentResults.asSequence()
        .filter { it.disposition == ContentDisposition.CONVERTED || it.disposition == ContentDisposition.DEGRADED }
        .forEach { content ->
            val outputPath = content.outputPath?.let(::normalized)
            if (outputPath == null || outputPath !in generatedPaths) {
                diagnostics += Diagnostic(
                    code = "STATIC_EXPORT_CONTENT_OUTPUT_MISSING",
                    severity = DiagnosticSeverity.ERROR,
                    message = "A converted/degraded declaration result has no matching generated content file.",
                    stage = ValidationStage.STRUCTURE,
                    location = content.location,
                    details = "${exporterId}: ${content.sourceSymbol} -> ${content.outputPath ?: "<none>"}",
                )
            }
        }
}
