package io.github.moddpbridge.runtimemapper

import io.github.moddpbridge.converter.ConvertedFileStatus
import io.github.moddpbridge.converter.RuntimePreparedContentResult
import io.github.moddpbridge.converter.RuntimePreparedConversion
import io.github.moddpbridge.converter.RuntimePreparedFile
import io.github.moddpbridge.converter.RuntimePreparedFileResult
import io.github.moddpbridge.converter.RuntimePreparedOutputNamespace
import io.github.moddpbridge.model.ContentDisposition
import io.github.moddpbridge.model.ContentKind
import io.github.moddpbridge.model.Diagnostic
import io.github.moddpbridge.model.DiagnosticSeverity
import io.github.moddpbridge.model.SourceLocation
import io.github.moddpbridge.model.ValidationStage
import io.github.moddpbridge.runtimeassets.RuntimeAssetDiagnostic
import io.github.moddpbridge.runtimeassets.RuntimeAssetDiagnosticSeverity
import io.github.moddpbridge.runtimeassets.RuntimeAssetSnapshot
import io.github.moddpbridge.runtimeassets.RuntimeAssetStager
import java.math.BigDecimal
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.Locale
import java.util.zip.ZipFile
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put

/** Mapping policy for the first runtime-snapshot-to-v159.7 milestone. */
data class RuntimeSnapshotMappingOptions(
    val includeAssets: Boolean = true,
    /** May only narrow the mapper's built-in milestone; it cannot enable unfinished content kinds. */
    val supportedContentTypes: Set<String> = setOf("item", "liquid", "status"),
)

data class RuntimeSnapshotMappingSummary(
    val snapshotSchemaVersion: Int,
    val targetMod: String,
    val observedContents: Int,
    val convertedContents: Int,
    val degradedContents: Int,
    val excludedContents: Int,
    val unsupportedContents: Int,
    val failedContents: Int,
    val generatedContentFiles: Int,
    val selectedAssetFiles: Int,
    val mappedFields: Int,
    val omittedNullFields: Int,
    val droppedFields: Int,
)

/**
 * Inert result of mapping a retained runtime snapshot. [prepared] contains only JSON/HJSON bytes
 * generated by this module and exact release-JAR asset references; no Mod classes are retained.
 */
data class RuntimeSnapshotMappingResult(
    val prepared: RuntimePreparedConversion,
    val summary: RuntimeSnapshotMappingSummary,
    val reportJson: String,
)

class RuntimeSnapshotMappingException(message: String, cause: Throwable? = null) : RuntimeException(message, cause)

/** Maps typed runtime snapshot schema v2 into the v159.7 DataPatcher declarative subset. */
object RuntimeSnapshotMapper {
    private const val supportedSnapshotSchema = 2
    private const val supportedSnapshotBuild = 159
    private const val supportedSnapshotRevision = 7
    private const val maxSnapshotBytes = 128L * 1024L * 1024L
    private val implementedContentTypes = setOf("item", "liquid", "status")
    private val json = Json {
        prettyPrint = true
        prettyPrintIndent = "  "
        explicitNulls = false
        ignoreUnknownKeys = true
    }

    fun prepare(
        snapshot: Path,
        modJar: Path,
        options: RuntimeSnapshotMappingOptions = RuntimeSnapshotMappingOptions(),
    ): RuntimeSnapshotMappingResult {
        val snapshotPath = snapshot.toAbsolutePath().normalize()
        val jarPath = modJar.toAbsolutePath().normalize()
        require(Files.isRegularFile(snapshotPath)) { "Runtime snapshot does not exist: $snapshotPath" }
        require(Files.isRegularFile(jarPath)) { "Release Mod JAR does not exist: $jarPath" }
        require(options.supportedContentTypes.all { it in implementedContentTypes }) {
            "supportedContentTypes may only narrow ${implementedContentTypes.sorted()}; " +
                "unfinished content mappings cannot be enabled by an option."
        }
        if (Files.size(snapshotPath) > maxSnapshotBytes) {
            throw RuntimeSnapshotMappingException(
                "Runtime snapshot exceeds the $maxSnapshotBytes byte safety limit: $snapshotPath",
            )
        }

        val root = try {
            json.parseToJsonElement(Files.readString(snapshotPath, StandardCharsets.UTF_8)).jsonObject
        } catch (error: Throwable) {
            throw RuntimeSnapshotMappingException("Could not parse runtime snapshot: $snapshotPath", error)
        }
        val schemaVersion = root.int("schemaVersion")
            ?: throw RuntimeSnapshotMappingException("Runtime snapshot has no integer schemaVersion.")
        if (schemaVersion != supportedSnapshotSchema) {
            throw RuntimeSnapshotMappingException(
                "Runtime snapshot schema $schemaVersion is unsupported; expected $supportedSnapshotSchema.",
            )
        }
        val targetMod = root.string("targetMod")?.takeIf(String::isNotBlank)
            ?: throw RuntimeSnapshotMappingException("Runtime snapshot has no targetMod.")
        val contents = root["contents"] as? JsonArray
            ?: throw RuntimeSnapshotMappingException("Runtime snapshot has no contents array.")
        validateSnapshotHeader(root, targetMod, contents)

        val provenanceIndex = try {
            JarProvenanceIndex.read(jarPath)
        } catch (error: Throwable) {
            throw RuntimeSnapshotMappingException("Could not index release-JAR provenance: $jarPath", error)
        }

        val diagnostics = mutableListOf<Diagnostic>()
        val logs = mutableListOf<String>()
        val preparedFiles = mutableListOf<RuntimePreparedFile>()
        val contentResults = mutableListOf<RuntimePreparedContentResult>()
        val fieldOutcomes = mutableListOf<FieldOutcome>()
        val phaseDifferences = mutableListOf<PhaseDifference>()
        val seenOutputPaths = hashSetOf<String>()

        logs += "Mapping runtime snapshot schema $schemaVersion for Mod '$targetMod'."
        contents.forEachIndexed { index, element ->
            val content = element as? JsonObject
            if (content == null) {
                diagnostics += diagnostic(
                    code = "RUNTIME_CONTENT_RECORD_INVALID",
                    severity = DiagnosticSeverity.ERROR,
                    message = "Runtime content record $index is not an object.",
                    snapshotPath = snapshotPath,
                    jsonPath = "$.contents[$index]",
                )
                contentResults += RuntimePreparedContentResult(
                    sourceSymbol = "<contents[$index]>",
                    disposition = ContentDisposition.FAILED,
                    reason = "Runtime snapshot record is not an object.",
                    diagnosticCodes = listOf("RUNTIME_CONTENT_RECORD_INVALID"),
                    location = SourceLocation(snapshotPath.toString(), "$.contents[$index]"),
                )
                return@forEachIndexed
            }
            val filesBefore = preparedFiles.size
            val resultsBefore = contentResults.size
            val diagnosticsBefore = diagnostics.size
            val fieldsBefore = fieldOutcomes.size
            val differencesBefore = phaseDifferences.size
            val pathsBefore = seenOutputPaths.toSet()
            try {
                mapContent(
                    content = content,
                    index = index,
                    targetMod = targetMod,
                    snapshotPath = snapshotPath,
                    options = options,
                    preparedFiles = preparedFiles,
                    contentResults = contentResults,
                    diagnostics = diagnostics,
                    fieldOutcomes = fieldOutcomes,
                    phaseDifferences = phaseDifferences,
                    seenOutputPaths = seenOutputPaths,
                    provenanceIndex = provenanceIndex,
                )
            } catch (error: Exception) {
                preparedFiles.truncate(filesBefore)
                contentResults.truncate(resultsBefore)
                diagnostics.truncate(diagnosticsBefore)
                fieldOutcomes.truncate(fieldsBefore)
                phaseDifferences.truncate(differencesBefore)
                seenOutputPaths.retainAll(pathsBefore)
                val sourceName = content.string("name") ?: "<contents[$index]>"
                diagnostics += diagnostic(
                    code = "RUNTIME_CONTENT_MAPPING_FAILED",
                    severity = DiagnosticSeverity.ERROR,
                    message = "Runtime content '$sourceName' could not be mapped safely.",
                    snapshotPath = snapshotPath,
                    jsonPath = "$.contents[$index]",
                    details = "${error::class.java.name}: ${error.message ?: "no message"}",
                )
                contentResults += RuntimePreparedContentResult(
                    sourceSymbol = sourceName,
                    disposition = ContentDisposition.FAILED,
                    sourceType = content.string("contentType"),
                    reason = "The mapper rejected an invalid or inconsistent runtime record.",
                    diagnosticCodes = listOf("RUNTIME_CONTENT_MAPPING_FAILED"),
                    location = SourceLocation(snapshotPath.toString(), "$.contents[$index]"),
                )
            }
        }

        var assetSnapshot: RuntimeAssetSnapshot? = null
        if (options.includeAssets) {
            assetSnapshot = try {
                RuntimeAssetStager.scanForRuntimeMapper(jarPath)
            } catch (error: Throwable) {
                throw RuntimeSnapshotMappingException("Runtime asset staging failed for $jarPath: ${error.message}", error)
            }
            assetSnapshot.diagnostics.forEach { diagnostics += it.toModelDiagnostic(jarPath) }
            assetSnapshot.files.forEach { asset ->
                preparedFiles += RuntimePreparedFile(
                    outputPath = asset.outputPath,
                    sourcePaths = listOf(asset.sourceEntryPath),
                    bytes = null,
                    namespace = RuntimePreparedOutputNamespace.SOURCE,
                    reason = "Exact runtime-loadable ${asset.kind.name.lowercase()} asset selected from the release JAR.",
                )
            }
            logs += "Selected ${assetSnapshot.files.size} exact release-JAR assets " +
                "(${assetSnapshot.stagedBytes} bytes, staging SHA-256 ${assetSnapshot.stagingSha256})."
        } else {
            logs += "Runtime asset staging was disabled by the caller."
        }

        val executableFileResults = buildExecutableFileResults(
            provenanceIndex = provenanceIndex,
            contents = contents,
            contentResults = contentResults,
            targetMod = targetMod,
            preparedFiles = preparedFiles,
        )
        logs += "Assigned explicit outcomes to ${executableFileResults.size} executable release-JAR entries " +
            "that did not directly produce an emitted file."

        phaseDifferences.forEach { difference ->
            diagnostics += diagnostic(
                code = "RUNTIME_PHASE_VALUE_CHANGED",
                severity = DiagnosticSeverity.INFO,
                message = "A mapped field changed after the ${difference.authoritativePhase} snapshot; " +
                    "the earliest available registration snapshot remains authoritative.",
                snapshotPath = snapshotPath,
                jsonPath = difference.jsonPath,
                details = "${difference.contentName}.${difference.field}: ${difference.phases.joinToString()}",
                suggestion = "If v159.7 validation or gameplay differs, inspect whether this was a base init derivation or custom Mod code.",
            )
        }

        val converted = contentResults.count { it.disposition == ContentDisposition.CONVERTED }
        val degraded = contentResults.count { it.disposition == ContentDisposition.DEGRADED }
        val excluded = contentResults.count { it.disposition == ContentDisposition.EXCLUDED }
        val unsupported = contentResults.count { it.disposition == ContentDisposition.UNSUPPORTED }
        val failed = contentResults.count { it.disposition == ContentDisposition.FAILED }
        val generatedContentFiles = preparedFiles.count { it.outputPath.startsWith("content/") }
        val summary = RuntimeSnapshotMappingSummary(
            snapshotSchemaVersion = schemaVersion,
            targetMod = targetMod,
            observedContents = contents.size,
            convertedContents = converted,
            degradedContents = degraded,
            excludedContents = excluded,
            unsupportedContents = unsupported,
            failedContents = failed,
            generatedContentFiles = generatedContentFiles,
            selectedAssetFiles = assetSnapshot?.files?.size ?: 0,
            mappedFields = fieldOutcomes.count { it.disposition == FieldDisposition.MAPPED },
            omittedNullFields = fieldOutcomes.count { it.disposition == FieldDisposition.OMITTED_NULL },
            droppedFields = fieldOutcomes.count { it.disposition == FieldDisposition.DROPPED },
        )
        logs += "Runtime mapper emitted $generatedContentFiles content declarations: " +
            "$converted converted, $degraded degraded; $excluded excluded, $unsupported unsupported, and $failed failed records were not emitted."

        val metadata = buildMap {
            put("runtimeSnapshotSchema", schemaVersion.toString())
            put("runtimeTargetMod", targetMod)
            put("runtimeSnapshotSha256", sha256(snapshotPath))
            put("runtimeObservedContents", contents.size.toString())
            put("runtimeGeneratedContents", generatedContentFiles.toString())
            put("runtimeConvertedContents", converted.toString())
            put("runtimeDegradedContents", degraded.toString())
            put("runtimeExcludedContents", excluded.toString())
            put("runtimeUnsupportedContents", unsupported.toString())
            put("runtimeFailedContents", failed.toString())
            put("runtimeMappedFields", summary.mappedFields.toString())
            put("runtimeDroppedFields", summary.droppedFields.toString())
            put("runtimeReleaseJarSha256", sha256(jarPath))
            put("runtimeExecutableOutcomes", executableFileResults.size.toString())
            assetSnapshot?.let {
                put("runtimeSelectedAssets", it.files.size.toString())
                put("runtimeAssetStagingSha256", it.stagingSha256)
            }
        }
        val prepared = RuntimePreparedConversion(
            files = preparedFiles.sortedBy { it.outputPath.lowercase(Locale.ROOT) },
            fileResults = executableFileResults,
            contentResults = contentResults,
            diagnostics = diagnostics,
            logs = logs,
            metadata = metadata,
            replaceOriginalContent = true,
        )
        return RuntimeSnapshotMappingResult(
            prepared = prepared,
            summary = summary,
            reportJson = buildReport(
                snapshotPath = snapshotPath,
                jarPath = jarPath,
                summary = summary,
                contentResults = contentResults,
                fieldOutcomes = fieldOutcomes,
                phaseDifferences = phaseDifferences,
                diagnostics = diagnostics,
                assetSnapshot = assetSnapshot,
            ),
        )
    }

    private fun mapContent(
        content: JsonObject,
        index: Int,
        targetMod: String,
        snapshotPath: Path,
        options: RuntimeSnapshotMappingOptions,
        preparedFiles: MutableList<RuntimePreparedFile>,
        contentResults: MutableList<RuntimePreparedContentResult>,
        diagnostics: MutableList<Diagnostic>,
        fieldOutcomes: MutableList<FieldOutcome>,
        phaseDifferences: MutableList<PhaseDifference>,
        seenOutputPaths: MutableSet<String>,
        provenanceIndex: JarProvenanceIndex,
    ) {
        val basePath = "$.contents[$index]"
        val sourceName = content.string("name")?.takeIf(String::isNotBlank) ?: "<contents[$index]>"
        val sourceType = content.string("contentType")
        val kind = sourceType?.let(::contentKind)
        val owner = content.string("modName")
        if (owner == null) {
            addFailedContent(
                sourceName, kind, sourceType, "RUNTIME_CONTENT_OWNER_MISSING",
                "Runtime content '$sourceName' has no owning Mod identity.", basePath, snapshotPath,
                diagnostics, contentResults,
            )
            return
        }
        if (!owner.equals(targetMod, ignoreCase = true)) {
            contentResults += RuntimePreparedContentResult(
                sourceSymbol = sourceName,
                kind = kind,
                disposition = ContentDisposition.EXCLUDED,
                sourceType = sourceType,
                reason = "The registration belongs to dependency Mod '$owner', not target Mod '$targetMod'.",
                diagnosticCodes = listOf("DEPENDENCY_CONTENT_EXCLUDED"),
                location = SourceLocation(snapshotPath.toString(), basePath),
            )
            return
        }
        if (sourceType == null || sourceType !in options.supportedContentTypes || sourceType !in implementedContentTypes || kind == null) {
            contentResults += RuntimePreparedContentResult(
                sourceSymbol = sourceName,
                kind = kind,
                disposition = ContentDisposition.UNSUPPORTED,
                sourceType = sourceType,
                reason = "Content type '${sourceType ?: "unknown"}' is outside the current runtime mapper milestone.",
                diagnosticCodes = listOf("RUNTIME_CONTENT_TYPE_NOT_MAPPED"),
                location = SourceLocation(snapshotPath.toString(), basePath),
            )
            diagnostics += diagnostic(
                code = "RUNTIME_CONTENT_TYPE_NOT_MAPPED",
                severity = DiagnosticSeverity.WARNING,
                message = "Runtime content '$sourceName' (${sourceType ?: "unknown"}) was retained in the report but not emitted.",
                snapshotPath = snapshotPath,
                jsonPath = basePath,
                suggestion = "Unit/weapon and block/factory mappings are subsequent milestones.",
            )
            return
        }

        val runtimeClass = content.string("runtimeClass")?.takeIf(String::isNotBlank)
        if (runtimeClass == null) {
            addFailedContent(
                sourceName, kind, sourceType, "RUNTIME_CONTENT_CLASS_MISSING",
                "Runtime content '$sourceName' has no runtimeClass.", "$basePath.runtimeClass", snapshotPath,
                diagnostics, contentResults,
            )
            return
        }

        val localName = localContentName(sourceName, targetMod)
        if (!validLocalName(localName)) {
            diagnostics += diagnostic(
                code = "RUNTIME_CONTENT_NAME_INVALID",
                severity = DiagnosticSeverity.ERROR,
                message = "Runtime content '$sourceName' cannot be represented as a safe DP content basename.",
                snapshotPath = snapshotPath,
                jsonPath = "$basePath.name",
            )
            contentResults += RuntimePreparedContentResult(
                sourceSymbol = sourceName,
                kind = kind,
                disposition = ContentDisposition.FAILED,
                sourceType = sourceType,
                reason = "Unsafe or empty local content name '$localName'.",
                diagnosticCodes = listOf("RUNTIME_CONTENT_NAME_INVALID"),
                location = SourceLocation(snapshotPath.toString(), "$basePath.name"),
            )
            return
        }
        val outputPath = "content/${kind.folderName}/$localName.hjson"

        val provenance = provenanceIndex.forContent(content)
        if (provenance == null) {
            diagnostics += diagnostic(
                code = "RUNTIME_CONTENT_PROVENANCE_MISSING",
                severity = DiagnosticSeverity.ERROR,
                message = "No exact release-JAR runtimeClass or registration-stack class can substantiate runtime content '$sourceName'.",
                snapshotPath = snapshotPath,
                jsonPath = basePath,
                suggestion = "Verify that the snapshot and release JAR are from the same build.",
            )
            contentResults += RuntimePreparedContentResult(
                sourceSymbol = sourceName,
                kind = kind,
                disposition = ContentDisposition.FAILED,
                sourceType = sourceType,
                reason = "Snapshot/JAR provenance could not be linked.",
                diagnosticCodes = listOf("RUNTIME_CONTENT_PROVENANCE_MISSING"),
                location = SourceLocation(snapshotPath.toString(), basePath),
            )
            return
        }

        val phaseResult = validateContentSnapshots(content, sourceName, sourceType, runtimeClass, basePath)
        if (phaseResult is PhaseValidation.Invalid) {
            diagnostics += diagnostic(
                code = phaseResult.code,
                severity = DiagnosticSeverity.ERROR,
                message = phaseResult.message,
                snapshotPath = snapshotPath,
                jsonPath = phaseResult.jsonPath,
                details = phaseResult.details,
            )
            contentResults += RuntimePreparedContentResult(
                sourceSymbol = sourceName,
                kind = kind,
                disposition = ContentDisposition.FAILED,
                sourceType = sourceType,
                reason = "The three-phase runtime snapshot contract is incomplete or inconsistent.",
                diagnosticCodes = listOf(phaseResult.code),
                location = SourceLocation(snapshotPath.toString(), phaseResult.jsonPath),
            )
            return
        }
        phaseResult as PhaseValidation.Valid
        val authoritative = phaseResult.authoritative
        val fields = phaseResult.authoritativeFields
        val authoritativePath = "$basePath.runtimeSnapshots.${phaseResult.authoritativeKey}"

        val output = linkedMapOf<String, JsonElement>()
        val contentDiagnosticCodes = linkedSetOf<String>()
        val targetType = resolveTargetParser(
            sourceType,
            authoritative,
            phaseResult.authoritativeKey,
            output,
            diagnostics,
            contentDiagnosticCodes,
            snapshotPath,
            basePath,
        )
        var degraded = targetType.degraded
        if (phaseResult.authoritativePhase != "PRE_CONTENT_INIT") {
            degraded = true
            contentDiagnosticCodes += "RUNTIME_CONTENT_REGISTERED_LATE"
            diagnostics += diagnostic(
                code = "RUNTIME_CONTENT_REGISTERED_LATE",
                severity = DiagnosticSeverity.WARNING,
                message = "Runtime content '$sourceName' was first observed in ${phaseResult.authoritativePhase}; " +
                    "that later snapshot was used because no PRE_CONTENT_INIT registration exists.",
                snapshotPath = snapshotPath,
                jsonPath = authoritativePath,
                suggestion = "Review fields derived by init/event handlers; DataPatcher validation proves loadability, not behavioral equivalence.",
            )
        }
        val fieldSpecs = fieldSpecs(sourceType, targetType.parserName)
        val missingFields = fieldSpecs.keys - fields.keys
        if (missingFields.isNotEmpty()) {
            addFailedContent(
                sourceName, kind, sourceType, "RUNTIME_REQUIRED_FIELDS_MISSING",
                "Runtime content '$sourceName' is missing required schema-v2 fields.",
                "$authoritativePath.fields", snapshotPath, diagnostics, contentResults,
                details = missingFields.sorted().joinToString(),
            )
            return
        }
        fields.forEach { (field, typed) ->
            val fieldPath = "$authoritativePath.fields.$field"
            val spec = fieldSpecs[field]
            val conversion = if (spec == null) {
                ValueConversion.Dropped(
                    runtimeKind(typed),
                    "RUNTIME_FIELD_NOT_ALLOWED",
                    "Field '$field' is not in the fixed v159.7 $sourceType/${targetType.parserName} mapper schema.",
                )
            } else {
                convertTypedValue(typed, fieldPath, spec)
            }
            when (conversion) {
                is ValueConversion.Mapped -> {
                    output[field] = conversion.value
                    fieldOutcomes += FieldOutcome(sourceName, field, FieldDisposition.MAPPED, conversion.kind, null, fieldPath)
                }
                ValueConversion.Null -> {
                    fieldOutcomes += FieldOutcome(sourceName, field, FieldDisposition.OMITTED_NULL, "null", "Null values use the target default.", fieldPath)
                }
                is ValueConversion.Dropped -> {
                    degraded = true
                    contentDiagnosticCodes += conversion.code
                    fieldOutcomes += FieldOutcome(sourceName, field, FieldDisposition.DROPPED, conversion.kind, conversion.reason, fieldPath)
                    diagnostics += diagnostic(
                        code = conversion.code,
                        severity = DiagnosticSeverity.WARNING,
                        message = "Runtime field '$sourceName.$field' was not serialized into DP HJSON.",
                        snapshotPath = snapshotPath,
                        jsonPath = fieldPath,
                        details = conversion.reason,
                        suggestion = "Add a manual v159.7-compatible field/effect when this changes map gameplay.",
                    )
                }
            }
        }

        val behaviorLosses = collectBehaviorLosses(
            authoritative,
            phaseResult.authoritativeKey,
            sourceName,
            snapshotPath,
            basePath,
            diagnostics,
        )
        if (behaviorLosses.isNotEmpty()) {
            degraded = true
            contentDiagnosticCodes += behaviorLosses
        }
        collectPhaseDifferences(
            content,
            sourceName,
            basePath,
            phaseResult.authoritativeKey,
            phaseResult.authoritativePhase,
            fields,
            output.keys,
            phaseDifferences,
        )

        if (!seenOutputPaths.add(outputPath.lowercase(Locale.ROOT))) {
            addFailedContent(
                sourceName, kind, sourceType, "RUNTIME_CONTENT_NAME_COLLISION",
                "Multiple runtime registrations map to '$outputPath'.", basePath, snapshotPath,
                diagnostics, contentResults,
            )
            return
        }

        val hjson = json.encodeToString(JsonObject(output)) + "\n"
        preparedFiles += RuntimePreparedFile(
            outputPath = outputPath,
            sourcePaths = listOf(provenance),
            bytes = hjson.toByteArray(StandardCharsets.UTF_8),
            namespace = RuntimePreparedOutputNamespace.SOURCE,
            reason = "Generated from ${phaseResult.authoritativePhase} typed runtime fields for '$sourceName'.",
        )
        contentResults += RuntimePreparedContentResult(
            sourceSymbol = sourceName,
            kind = kind,
            disposition = if (degraded) ContentDisposition.DEGRADED else ContentDisposition.CONVERTED,
            sourceType = runtimeClass,
            targetType = targetType.parserName,
            outputName = "dp-$localName",
            outputPath = outputPath,
            reason = if (degraded) {
                "Loadable base fields were emitted; custom/opaque behavior remains explicitly reported."
            } else {
                "All captured ${phaseResult.authoritativePhase} fields were representable in v159.7 DP HJSON."
            },
            diagnosticCodes = contentDiagnosticCodes.toList(),
            location = SourceLocation(snapshotPath.toString(), basePath),
        )
    }

    private fun resolveTargetParser(
        sourceType: String,
        authoritative: JsonObject,
        authoritativeKey: String,
        output: MutableMap<String, JsonElement>,
        diagnostics: MutableList<Diagnostic>,
        codes: MutableSet<String>,
        snapshotPath: Path,
        basePath: String,
    ): TargetParserDecision {
        val canonical = canonicalParserName(sourceType)
        val fallback = authoritative["sourceClassMapFallback"] as? JsonObject
        val parserName = fallback?.string("parserName")
        val loadableRoot = (fallback?.get("loadableRoot") as? JsonPrimitive)?.booleanOrNull
        val allowed = allowedParserNames.getValue(sourceType)
        if (parserName == null || loadableRoot != true || parserName !in allowed || !SAFE_PARSER_NAME.matches(parserName)) {
            val code = "RUNTIME_CLASS_FALLBACK_UNLOADABLE"
            codes += code
            diagnostics += diagnostic(
                code = code,
                severity = DiagnosticSeverity.WARNING,
                message = "The observed runtime class fallback is not an approved v159.7 $sourceType parser; base $canonical is used.",
                snapshotPath = snapshotPath,
                jsonPath = "$basePath.runtimeSnapshots.$authoritativeKey.sourceClassMapFallback",
                details = "parserName=${parserName ?: "<missing>"}, loadableRoot=${loadableRoot ?: "<invalid>"}, allowed=${allowed.sorted()}",
            )
            return TargetParserDecision(canonical, degraded = true)
        }
        if (parserName != canonical) output["type"] = JsonPrimitive(parserName)
        return TargetParserDecision(parserName, degraded = false)
    }

    private fun convertTypedValue(element: JsonElement, jsonPath: String, spec: FieldSpec): ValueConversion {
        val value = element as? JsonObject
            ?: return ValueConversion.Dropped("unknown", "RUNTIME_TYPED_VALUE_INVALID", "Typed value is not an object at $jsonPath.")
        val declaredType = value.string("declaredType")
            ?: return ValueConversion.Dropped("unknown", "RUNTIME_TYPED_VALUE_INVALID", "Typed value has no declaredType.")
        val kind = value.string("kind")
            ?: return ValueConversion.Dropped("unknown", "RUNTIME_TYPED_VALUE_INVALID", "Typed value has no kind discriminator.")
        if (kind != "null" && kind !in spec.kinds) {
            return ValueConversion.Dropped(
                kind,
                "RUNTIME_FIELD_KIND_MISMATCH",
                "Runtime kind '$kind' (declaredType=$declaredType) is not allowed; expected ${spec.kinds.sorted()}.",
            )
        }
        return when (kind) {
            "null" -> ValueConversion.Null
            "boolean" -> (value["value"] as? JsonPrimitive)?.booleanOrNull?.let {
                ValueConversion.Mapped(JsonPrimitive(it), kind)
            } ?: ValueConversion.Dropped(kind, "RUNTIME_TYPED_VALUE_INVALID", "Boolean value is missing or invalid.")
            "number" -> {
                val numberType = value.string("numberType")
                if (numberType !in spec.numberTypes) {
                    ValueConversion.Dropped(
                        kind,
                        "RUNTIME_NUMBER_TYPE_MISMATCH",
                        "numberType '${numberType ?: "<missing>"}' is not allowed; expected ${spec.numberTypes.sorted()}.",
                    )
                } else {
                    numberValue(value.string("value"), numberType)
                }
            }
            "string", "enum" -> value.string("value")?.let { ValueConversion.Mapped(JsonPrimitive(it), kind) }
                ?: ValueConversion.Dropped(kind, "RUNTIME_TYPED_VALUE_INVALID", "String/enum value is missing.")
            "color" -> value.string("rgba")?.takeIf { it.matches(COLOR) }?.let {
                ValueConversion.Mapped(JsonPrimitive(it.lowercase(Locale.ROOT)), kind)
            } ?: ValueConversion.Dropped(kind, "RUNTIME_COLOR_INVALID", "RGBA value is absent or not 8 hexadecimal digits.")
            "contentRef" -> {
                val name = value.string("name")?.takeIf(::validReferenceName)
                val contentType = value.string("contentType")
                if (name == null || contentType != spec.contentReferenceType) {
                    ValueConversion.Dropped(
                        kind,
                        "RUNTIME_CONTENT_REFERENCE_INVALID",
                        "Content reference name/type is invalid: name=${name ?: "<invalid>"}, type=${contentType ?: "<missing>"}, expected=${spec.contentReferenceType}.",
                    )
                } else {
                    ValueConversion.Mapped(JsonPrimitive(name), kind)
                }
            }
            "staticRef" -> {
                val owner = value.string("owner")
                val field = value.string("field")
                val parserValue = value.string("parserValue")
                if (owner == "mindustry.content.Fx" && field != null && parserValue == field && SAFE_PARSER_NAME.matches(field)) {
                    ValueConversion.Mapped(JsonPrimitive(parserValue), kind)
                } else {
                    ValueConversion.Dropped(
                        kind,
                        "RUNTIME_STATIC_REFERENCE_UNMAPPABLE",
                        "Only exact mindustry.content.Fx field identities are accepted (owner=$owner, field=$field, parserValue=$parserValue).",
                    )
                }
            }
            "array" -> {
                val truncated = (value["truncated"] as? JsonPrimitive)?.booleanOrNull
                    ?: return ValueConversion.Dropped(kind, "RUNTIME_TYPED_VALUE_INVALID", "Array has no valid truncated flag.")
                val elementSpec = spec.elementSpec
                    ?: return ValueConversion.Dropped(kind, "RUNTIME_FIELD_KIND_MISMATCH", "This field does not allow an array value.")
                if (truncated) {
                    ValueConversion.Dropped(kind, "RUNTIME_ARRAY_TRUNCATED", "The runtime extractor truncated this collection.")
                } else {
                    val values = value["values"] as? JsonArray
                        ?: return ValueConversion.Dropped(kind, "RUNTIME_TYPED_VALUE_INVALID", "Array has no values list.")
                    val converted = mutableListOf<JsonElement>()
                    values.forEachIndexed { index, child ->
                        when (val childResult = convertTypedValue(child, "$jsonPath.values[$index]", elementSpec)) {
                            is ValueConversion.Mapped -> converted += childResult.value
                            ValueConversion.Null -> converted += JsonNull
                            is ValueConversion.Dropped -> return ValueConversion.Dropped(
                                kind,
                                childResult.code,
                                "Array element $index could not be represented: ${childResult.reason}",
                            )
                        }
                    }
                    ValueConversion.Mapped(JsonArray(converted), kind)
                }
            }
            "opaque" -> ValueConversion.Dropped(
                kind,
                "RUNTIME_FIELD_OPAQUE",
                listOfNotNull(value.string("reason"), value.string("runtimeClass"), value.string("detail")).joinToString(": ")
                    .ifBlank { "Extractor deliberately represented the object as opaque." },
            )
            else -> ValueConversion.Dropped(kind, "RUNTIME_TYPED_VALUE_UNSUPPORTED", "Unsupported typed value kind '$kind'.")
        }
    }

    private fun numberValue(raw: String?, numberType: String?): ValueConversion {
        if (raw == null) return ValueConversion.Dropped("number", "RUNTIME_NUMBER_INVALID", "Number value is missing.")
        val decimal = runCatching { BigDecimal(raw) }.getOrNull()
            ?: return ValueConversion.Dropped("number", "RUNTIME_NUMBER_INVALID", "Non-finite or invalid number '$raw'.")
        return if (numberType in setOf("byte", "short", "int", "long", "bigInteger")) {
            val integer = runCatching { decimal.toBigIntegerExact() }.getOrNull()
                ?: return ValueConversion.Dropped(
                    "number",
                    "RUNTIME_NUMBER_INVALID",
                    "Integer field contains fractional value '$raw'.",
                )
            ValueConversion.Mapped(JsonPrimitive(integer), "number")
        } else {
            ValueConversion.Mapped(JsonPrimitive(decimal), "number")
        }
    }

    private fun collectBehaviorLosses(
        authoritative: JsonObject,
        authoritativeKey: String,
        sourceName: String,
        snapshotPath: Path,
        basePath: String,
        diagnostics: MutableList<Diagnostic>,
    ): Set<String> {
        val codes = linkedSetOf<String>()
        fun stringList(name: String): List<String> = (authoritative[name] as? JsonArray).orEmpty().mapNotNull {
            (it as? JsonPrimitive)?.contentOrNull
        }
        val behaviorGroups = listOf(
            Triple("customFields", "RUNTIME_CUSTOM_FIELD_NOT_SERIALIZED", "Custom Java fields are not part of DataPatcher HJSON."),
            Triple("overriddenMethods", "RUNTIME_OVERRIDDEN_METHOD_NOT_SERIALIZED", "Overridden Java behavior cannot be serialized."),
            Triple("customOnlyMethods", "RUNTIME_CUSTOM_METHOD_NOT_SERIALIZED", "Custom-only Java methods cannot be serialized."),
        )
        behaviorGroups.forEach { (field, code, message) ->
            val values = stringList(field)
            if (values.isNotEmpty()) {
                codes += code
                diagnostics += diagnostic(
                    code = code,
                    severity = DiagnosticSeverity.WARNING,
                    message = "$sourceName: $message",
                    snapshotPath = snapshotPath,
                    jsonPath = "$basePath.runtimeSnapshots.$authoritativeKey.$field",
                    details = values.joinToString("; "),
                    suggestion = "Reimplement only gameplay-relevant behavior with v159.7-supported fields/effects.",
                )
            }
        }
        (authoritative["declaredLosses"] as? JsonArray).orEmpty().forEachIndexed { index, lossElement ->
            val loss = lossElement as? JsonObject ?: return@forEachIndexed
            val code = loss.string("reason")?.takeIf(String::isNotBlank) ?: "RUNTIME_DECLARED_BEHAVIOR_LOSS"
            codes += code
            diagnostics += diagnostic(
                code = code,
                severity = DiagnosticSeverity.WARNING,
                message = "$sourceName: ${loss.string("detail") ?: "The extractor declared an unserializable runtime behavior."}",
                snapshotPath = snapshotPath,
                jsonPath = "$basePath.runtimeSnapshots.$authoritativeKey.declaredLosses[$index]",
                details = loss.string("field"),
            )
        }
        return codes
    }

    private fun collectPhaseDifferences(
        content: JsonObject,
        sourceName: String,
        basePath: String,
        authoritativeKey: String,
        authoritativePhase: String,
        authoritativeFields: JsonObject,
        mappedFields: Set<String>,
        output: MutableList<PhaseDifference>,
    ) {
        val snapshots = content["runtimeSnapshots"] as? JsonObject ?: return
        val phaseOrder = listOf(
            "preContentInit" to "PRE_CONTENT_INIT",
            "postContentInit" to "POST_CONTENT_INIT",
            "finalAfterModInit" to "FINAL_AFTER_MOD_INIT",
        )
        val authoritativeIndex = phaseOrder.indexOfFirst { it.first == authoritativeKey }
        authoritativeFields.forEach { (field, baseline) ->
            if (field !in mappedFields) return@forEach
            val phases = linkedMapOf(authoritativePhase to baseline)
            phaseOrder.drop(authoritativeIndex + 1).forEach { (key, phaseName) ->
                val value = ((snapshots[key] as? JsonObject)?.get("fields") as? JsonObject)?.get(field)
                if (value != null && value != baseline) phases[phaseName] = value
            }
            if (phases.size > 1) {
                output += PhaseDifference(
                    contentName = sourceName,
                    field = field,
                    jsonPath = "$basePath.runtimeSnapshots",
                    phases = phases.map { (phase, value) -> "$phase=${compactTypedValue(value)}" },
                    authoritativePhase = authoritativePhase,
                )
            }
        }
    }

    private fun buildReport(
        snapshotPath: Path,
        jarPath: Path,
        summary: RuntimeSnapshotMappingSummary,
        contentResults: List<RuntimePreparedContentResult>,
        fieldOutcomes: List<FieldOutcome>,
        phaseDifferences: List<PhaseDifference>,
        diagnostics: List<Diagnostic>,
        assetSnapshot: RuntimeAssetSnapshot?,
    ): String {
        val root = buildJsonObject {
            put("schemaVersion", 1)
            put("snapshot", buildJsonObject {
                put("path", snapshotPath.toString())
                put("sha256", sha256(snapshotPath))
                put("runtimeSchemaVersion", summary.snapshotSchemaVersion)
                put("targetMod", summary.targetMod)
            })
            put("releaseJar", buildJsonObject {
                put("path", jarPath.toString())
                put("sha256", sha256(jarPath))
            })
            put("summary", buildJsonObject {
                put("observedContents", summary.observedContents)
                put("convertedContents", summary.convertedContents)
                put("degradedContents", summary.degradedContents)
                put("excludedContents", summary.excludedContents)
                put("unsupportedContents", summary.unsupportedContents)
                put("failedContents", summary.failedContents)
                put("generatedContentFiles", summary.generatedContentFiles)
                put("selectedAssetFiles", summary.selectedAssetFiles)
                put("mappedFields", summary.mappedFields)
                put("omittedNullFields", summary.omittedNullFields)
                put("droppedFields", summary.droppedFields)
                put("infoDiagnostics", diagnostics.count { it.severity == DiagnosticSeverity.INFO })
                put("warningDiagnostics", diagnostics.count { it.severity == DiagnosticSeverity.WARNING })
                put("errorDiagnostics", diagnostics.count { it.severity == DiagnosticSeverity.ERROR })
            })
            put("contents", buildJsonArray {
                contentResults.forEach { result ->
                    add(buildJsonObject {
                        put("sourceSymbol", result.sourceSymbol)
                        result.kind?.let { put("kind", it.name.lowercase(Locale.ROOT)) }
                        put("disposition", result.disposition.name.lowercase(Locale.ROOT))
                        result.sourceType?.let { put("sourceType", it) }
                        result.targetType?.let { put("targetType", it) }
                        result.outputName?.let { put("outputName", it) }
                        result.outputPath?.let { put("outputPath", it) }
                        result.reason?.let { put("reason", it) }
                        put("diagnosticCodes", buildJsonArray {
                            result.diagnosticCodes.forEach { add(JsonPrimitive(it)) }
                        })
                    })
                }
            })
            put("fields", buildJsonArray {
                fieldOutcomes.forEach { outcome ->
                    add(buildJsonObject {
                        put("content", outcome.content)
                        put("field", outcome.field)
                        put("disposition", outcome.disposition.wireName)
                        put("runtimeKind", outcome.runtimeKind)
                        outcome.reason?.let { put("reason", it) }
                        put("snapshotPath", outcome.jsonPath)
                    })
                }
            })
            put("phaseDifferences", buildJsonArray {
                phaseDifferences.forEach { difference ->
                    add(buildJsonObject {
                        put("content", difference.contentName)
                        put("field", difference.field)
                        put("values", buildJsonArray {
                            difference.phases.forEach { add(JsonPrimitive(it)) }
                        })
                    })
                }
            })
            assetSnapshot?.let { assets ->
                put("assets", buildJsonObject {
                    if (assets.resolvedRootPrefix == null) {
                        put("resolvedRootPrefix", JsonNull)
                    } else {
                        put("resolvedRootPrefix", assets.resolvedRootPrefix)
                    }
                    put("scannedEntries", assets.scannedEntryCount)
                    put("candidateFiles", assets.candidateFileCount)
                    put("selectedFiles", assets.files.size)
                    put("selectedBytes", assets.stagedBytes)
                    put("stagingSha256", assets.stagingSha256)
                })
            }
            put("diagnostics", buildJsonArray {
                diagnostics.forEach { diagnostic ->
                    add(buildJsonObject {
                        put("code", diagnostic.code)
                        put("severity", diagnostic.severity.name.lowercase(Locale.ROOT))
                        put("message", diagnostic.message)
                        diagnostic.location?.path?.let { put("path", it) }
                        diagnostic.location?.jsonPath?.let { put("jsonPath", it) }
                        diagnostic.details?.let { put("details", it) }
                        diagnostic.suggestion?.let { put("suggestion", it) }
                    })
                }
            })
        }
        return json.encodeToString(root) + "\n"
    }

    private fun RuntimeAssetDiagnostic.toModelDiagnostic(jarPath: Path): Diagnostic = Diagnostic(
        code = code,
        severity = when (severity) {
            RuntimeAssetDiagnosticSeverity.INFO -> DiagnosticSeverity.INFO
            RuntimeAssetDiagnosticSeverity.WARNING -> DiagnosticSeverity.WARNING
            RuntimeAssetDiagnosticSeverity.ERROR -> DiagnosticSeverity.ERROR
        },
        message = message,
        stage = ValidationStage.STRUCTURE,
        location = SourceLocation(jarPath.toString(), sourceEntryPath?.let { "jar:$it" }),
        details = listOfNotNull(
            details,
            outputPath?.let { "output=$it" },
            relatedSourceEntryPaths.takeIf { it.isNotEmpty() }?.joinToString(prefix = "related=", separator = ","),
        ).joinToString("; ").ifBlank { null },
    )

    private fun diagnostic(
        code: String,
        severity: DiagnosticSeverity,
        message: String,
        snapshotPath: Path,
        jsonPath: String? = null,
        details: String? = null,
        suggestion: String? = null,
    ): Diagnostic = Diagnostic(
        code = code,
        severity = severity,
        message = message,
        stage = ValidationStage.STRUCTURE,
        location = SourceLocation(snapshotPath.toString(), jsonPath),
        details = details,
        suggestion = suggestion,
    )

    private fun validateSnapshotHeader(root: JsonObject, targetMod: String, contents: JsonArray) {
        val gameVersion = root["gameVersion"] as? JsonObject
            ?: throw RuntimeSnapshotMappingException("Runtime snapshot has no gameVersion object.")
        val build = gameVersion.int("build")
        val revision = gameVersion.int("revision")
        if (build != supportedSnapshotBuild || revision != supportedSnapshotRevision) {
            throw RuntimeSnapshotMappingException(
                "Runtime snapshot was captured from build $build revision $revision; " +
                    "this mapper currently requires v$supportedSnapshotBuild.$supportedSnapshotRevision exactly.",
            )
        }
        val loadedMod = root["loadedMod"] as? JsonObject
            ?: throw RuntimeSnapshotMappingException("Runtime snapshot has no loadedMod object.")
        val loadedName = loadedMod.string("name")
        if (loadedName == null || !loadedName.equals(targetMod, ignoreCase = true)) {
            throw RuntimeSnapshotMappingException(
                "Runtime snapshot targetMod '$targetMod' does not match loadedMod '${loadedName ?: "<missing>"}'.",
            )
        }
        root.int("contentCount")?.let { declared ->
            if (declared != contents.size) {
                throw RuntimeSnapshotMappingException(
                    "Runtime snapshot contentCount $declared does not match contents size ${contents.size}.",
                )
            }
        }
    }

    private fun validateContentSnapshots(
        content: JsonObject,
        sourceName: String,
        sourceType: String,
        runtimeClass: String,
        basePath: String,
    ): PhaseValidation {
        val snapshots = content["runtimeSnapshots"] as? JsonObject
            ?: return PhaseValidation.Invalid(
                "RUNTIME_PHASE_SNAPSHOT_INVALID",
                "Runtime content '$sourceName' has no runtimeSnapshots object.",
                "$basePath.runtimeSnapshots",
            )
        val phases = listOf(
            Triple("preContentInit", "PRE_CONTENT_INIT", "$basePath.runtimeSnapshots.preContentInit"),
            Triple("postContentInit", "POST_CONTENT_INIT", "$basePath.runtimeSnapshots.postContentInit"),
            Triple("finalAfterModInit", "FINAL_AFTER_MOD_INIT", "$basePath.runtimeSnapshots.finalAfterModInit"),
        )
        data class PresentPhase(
            val index: Int,
            val key: String,
            val phaseName: String,
            val path: String,
            val snapshot: JsonObject,
            val fields: JsonObject,
        )
        val present = mutableListOf<PresentPhase>()
        phases.forEachIndexed { index, (key, expectedPhase, path) ->
            val raw = snapshots[key]
            if (raw == null || raw is JsonNull) return@forEachIndexed
            val phase = raw as? JsonObject
                ?: return PhaseValidation.Invalid(
                    "RUNTIME_PHASE_SNAPSHOT_INVALID",
                    "Runtime content '$sourceName' has a non-object phase $expectedPhase.",
                    path,
                )
            if (phase.int("schemaVersion") != 1 || phase.string("phase") != expectedPhase ||
                phase.string("name") != sourceName || phase.string("contentType") != sourceType ||
                phase.string("runtimeClass") != runtimeClass
            ) {
                return PhaseValidation.Invalid(
                    "RUNTIME_PHASE_SNAPSHOT_INVALID",
                    "Runtime content '$sourceName' has inconsistent identity metadata in phase $expectedPhase.",
                    path,
                )
            }
            val phaseFields = phase["fields"] as? JsonObject
                ?: return PhaseValidation.Invalid(
                    "RUNTIME_PHASE_SNAPSHOT_INVALID",
                    "Runtime content '$sourceName' phase $expectedPhase has no fields object.",
                    "$path.fields",
                )
            present += PresentPhase(index, key, expectedPhase, path, phase, phaseFields)
        }
        if (present.none { it.key == "finalAfterModInit" }) {
            return PhaseValidation.Invalid(
                "RUNTIME_PHASE_SNAPSHOT_INVALID",
                "Runtime content '$sourceName' is missing the authoritative FINAL_AFTER_MOD_INIT phase.",
                "$basePath.runtimeSnapshots.finalAfterModInit",
            )
        }
        val firstIndex = present.first().index
        if (present.map { it.index } != (firstIndex..phases.lastIndex).toList()) {
            return PhaseValidation.Invalid(
                "RUNTIME_PHASE_PRESENCE_NON_MONOTONIC",
                "Runtime content '$sourceName' appears in a phase, disappears, and later reappears.",
                "$basePath.runtimeSnapshots",
                present.joinToString { it.phaseName },
            )
        }
        if (present.drop(1).any { it.fields.keys != present.first().fields.keys }) {
            return PhaseValidation.Invalid(
                "RUNTIME_PHASE_FIELD_SET_MISMATCH",
                "Runtime content '$sourceName' does not expose the same field set in every phase where it exists.",
                "$basePath.runtimeSnapshots",
                present.joinToString("; ") { "${it.phaseName}=${it.fields.keys.sorted()}" },
            )
        }
        val authoritative = present.first()
        return PhaseValidation.Valid(
            authoritative = authoritative.snapshot,
            authoritativeFields = authoritative.fields,
            authoritativeKey = authoritative.key,
            authoritativePhase = authoritative.phaseName,
        )
    }

    private fun addFailedContent(
        sourceName: String,
        kind: ContentKind?,
        sourceType: String?,
        code: String,
        message: String,
        jsonPath: String,
        snapshotPath: Path,
        diagnostics: MutableList<Diagnostic>,
        contentResults: MutableList<RuntimePreparedContentResult>,
        details: String? = null,
    ) {
        diagnostics += diagnostic(code, DiagnosticSeverity.ERROR, message, snapshotPath, jsonPath, details)
        contentResults += RuntimePreparedContentResult(
            sourceSymbol = sourceName,
            kind = kind,
            disposition = ContentDisposition.FAILED,
            sourceType = sourceType,
            reason = message,
            diagnosticCodes = listOf(code),
            location = SourceLocation(snapshotPath.toString(), jsonPath),
        )
    }

    private fun buildExecutableFileResults(
        provenanceIndex: JarProvenanceIndex,
        contents: JsonArray,
        contentResults: List<RuntimePreparedContentResult>,
        targetMod: String,
        preparedFiles: List<RuntimePreparedFile>,
    ): List<RuntimePreparedFileResult> {
        val emittedSources = preparedFiles.flatMapTo(hashSetOf()) { it.sourcePaths }
        val unsupportedSources = hashSetOf<String>()
        contents.forEachIndexed { index, element ->
            val content = element as? JsonObject ?: return@forEachIndexed
            if (content.string("modName")?.equals(targetMod, ignoreCase = true) != true) return@forEachIndexed
            val disposition = contentResults.getOrNull(index)?.disposition ?: return@forEachIndexed
            if (disposition == ContentDisposition.UNSUPPORTED || disposition == ContentDisposition.FAILED) {
                provenanceIndex.forContent(content)?.let(unsupportedSources::add)
            }
        }
        return provenanceIndex.executableEntries.asSequence()
            .filterNot { it in emittedSources }
            .map { sourcePath ->
                val unsupported = sourcePath in unsupportedSources || provenanceIndex.isDynamicExecutable(sourcePath)
                RuntimePreparedFileResult(
                    sourcePath = sourcePath,
                    status = if (unsupported) ConvertedFileStatus.UNSUPPORTED else ConvertedFileStatus.EXCLUDED,
                    reason = if (unsupported) {
                        "The release Mod was executed, but this executable entry was not directly representable in the current v159.7 mapper milestone."
                    } else {
                        "The release Mod was executed; this helper/source entry had no direct emitted declaration or selected runtime asset."
                    },
                    diagnosticCodes = listOf(
                        if (unsupported) "RUNTIME_EXECUTABLE_NOT_MAPPED" else "RUNTIME_EXECUTABLE_NO_DIRECT_OUTPUT",
                    ),
                )
            }
            .sortedBy { it.sourcePath }
            .toList()
    }

    private fun fieldSpecs(sourceType: String, parserName: String): Map<String, FieldSpec> = when (sourceType) {
        "item" -> itemFieldSpecs
        "liquid" -> if (parserName == "CellLiquid") liquidFieldSpecs + cellLiquidFieldSpecs else liquidFieldSpecs
        "status" -> statusFieldSpecs
        else -> emptyMap()
    }

    private fun runtimeKind(value: JsonElement): String = (value as? JsonObject)?.string("kind") ?: "unknown"

    private fun JsonObject.string(name: String): String? = (this[name] as? JsonPrimitive)?.contentOrNull

    private fun JsonObject.int(name: String): Int? = (this[name] as? JsonPrimitive)?.intOrNull

    private fun <T> MutableList<T>.truncate(size: Int) {
        while (this.size > size) removeAt(lastIndex)
    }

    private fun contentKind(type: String): ContentKind? = when (type) {
        "item" -> ContentKind.ITEM
        "liquid" -> ContentKind.LIQUID
        "status" -> ContentKind.STATUS
        "block" -> ContentKind.BLOCK
        "unit" -> ContentKind.UNIT
        "weather" -> ContentKind.WEATHER
        else -> null
    }

    private fun canonicalParserName(type: String): String = when (type) {
        "item" -> "Item"
        "liquid" -> "Liquid"
        "status" -> "StatusEffect"
        else -> type
    }

    private fun localContentName(name: String, mod: String): String {
        val prefix = "$mod-"
        return if (name.startsWith(prefix, ignoreCase = true)) name.substring(prefix.length) else name
    }

    private fun validLocalName(name: String): Boolean = name.isNotBlank() && name.length <= 240 &&
        !name.endsWith('.') && !name.endsWith(' ') &&
        !name.contains('/') && !name.contains('\\') && name !in setOf(".", "..") &&
        name.none { it.code < 0x20 || it == ':' || it == '*' || it == '?' || it == '"' || it == '<' || it == '>' || it == '|' }

    private fun validReferenceName(name: String): Boolean = validLocalName(name) && name.length <= 240

    private fun compactTypedValue(value: JsonElement): String {
        val objectValue = value as? JsonObject ?: return value.toString().take(200)
        return when (objectValue.string("kind")) {
            "number", "string", "enum" -> objectValue.string("value") ?: objectValue.toString().take(200)
            "boolean" -> objectValue["value"]?.toString() ?: "?"
            "color" -> objectValue.string("rgba") ?: "?"
            "contentRef" -> objectValue.string("name") ?: "?"
            "staticRef" -> objectValue.string("parserValue") ?: objectValue.string("field") ?: "?"
            "null" -> "null"
            else -> objectValue.toString().take(200)
        }
    }

    private fun sha256(path: Path): String {
        val digest = MessageDigest.getInstance("SHA-256")
        Files.newInputStream(path).use { input ->
            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
            while (true) {
                val read = input.read(buffer)
                if (read < 0) break
                digest.update(buffer, 0, read)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }

    private sealed interface ValueConversion {
        data class Mapped(val value: JsonElement, val kind: String) : ValueConversion
        data object Null : ValueConversion
        data class Dropped(val kind: String, val code: String, val reason: String) : ValueConversion
    }

    private enum class FieldDisposition(val wireName: String) {
        MAPPED("mapped"),
        OMITTED_NULL("omittedNull"),
        DROPPED("dropped"),
    }

    private data class FieldOutcome(
        val content: String,
        val field: String,
        val disposition: FieldDisposition,
        val runtimeKind: String,
        val reason: String?,
        val jsonPath: String,
    )

    private data class PhaseDifference(
        val contentName: String,
        val field: String,
        val jsonPath: String,
        val phases: List<String>,
        val authoritativePhase: String,
    )

    private data class TargetParserDecision(val parserName: String, val degraded: Boolean)

    private data class FieldSpec(
        val kinds: Set<String>,
        val numberTypes: Set<String> = emptySet(),
        val contentReferenceType: String? = null,
        val elementSpec: FieldSpec? = null,
    )

    private sealed interface PhaseValidation {
        data class Valid(
            val authoritative: JsonObject,
            val authoritativeFields: JsonObject,
            val authoritativeKey: String,
            val authoritativePhase: String,
        ) : PhaseValidation

        data class Invalid(
            val code: String,
            val message: String,
            val jsonPath: String,
            val details: String? = null,
        ) : PhaseValidation
    }

    private data class JarProvenanceIndex(
        val entries: List<String>,
        val resolvedRoot: String?,
    ) {
        val executableEntries: List<String> = entries.filter(::looksExecutable)

        fun forContent(content: JsonObject): String? {
            val runtimeClass = content.string("runtimeClass")
            if (runtimeClass != null) {
                val classPath = runtimeClass.replace('.', '/') + ".class"
                entries.firstOrNull { it.equals(classPath, ignoreCase = true) }?.let { return it }
                entries.firstOrNull { it.endsWith("/$classPath", ignoreCase = true) }?.let { return it }
            }

            val stackClasses = (content["registrationStack"] as? JsonArray).orEmpty().mapNotNull { frame ->
                (frame as? JsonPrimitive)?.contentOrNull?.substringBefore('(')?.substringBeforeLast('.')
            }.filterNot { className ->
                className.startsWith("mindustry.") || className.startsWith("arc.") ||
                    className.startsWith("java.") || className.startsWith("javax.")
            }
            stackClasses.forEach { className ->
                val classPath = className.replace('.', '/') + ".class"
                entries.firstOrNull { it.equals(classPath, ignoreCase = true) }?.let { return it }
                entries.firstOrNull { it.endsWith("/$classPath", ignoreCase = true) }?.let { return it }
            }
            return null
        }

        fun isDynamicExecutable(path: String): Boolean {
            val relative = relative(path)
            val extension = relative.substringAfterLast('.', "").lowercase(Locale.ROOT)
            return extension in setOf("dex", "jar", "js", "kts") ||
                relative.startsWith("scripts/", ignoreCase = true) ||
                relative.startsWith("assets/scripts/", ignoreCase = true)
        }

        private fun looksExecutable(path: String): Boolean {
            val relative = relative(path)
            if (relative.startsWith("assets/", ignoreCase = true) &&
                !relative.startsWith("assets/scripts/", ignoreCase = true)
            ) return false
            if (relative.equals("gradle/wrapper/gradle-wrapper.jar", ignoreCase = true)) return false
            val extension = relative.substringAfterLast('.', "").lowercase(Locale.ROOT)
            return extension in setOf("class", "jar", "dex", "js", "kts", "java", "kt") ||
                relative.startsWith("scripts/", ignoreCase = true) ||
                relative.startsWith("assets/scripts/", ignoreCase = true)
        }

        private fun relative(path: String): String =
            resolvedRoot?.let { path.removePrefix("$it/") } ?: path

        companion object {
            fun read(jar: Path): JarProvenanceIndex {
                val entries = ZipFile(jar.toFile()).use { zip ->
                    zip.entries().asSequence()
                        .filterNot { it.isDirectory }
                        .map { entry ->
                            val replaced = entry.name.replace('\\', '/')
                            val parts = replaced.split('/')
                            if (replaced.startsWith('/') || ':' in replaced || '\u0000' in replaced ||
                                parts.any { it.isBlank() || it == "." || it == ".." }
                            ) {
                                throw RuntimeSnapshotMappingException("Unsafe release-JAR entry path: ${entry.name}")
                            }
                            parts.joinToString("/")
                        }
                        .filter(String::isNotBlank)
                        .take(100_001)
                        .toList()
                }
                if (entries.size > 100_000) {
                    throw RuntimeSnapshotMappingException("Release JAR contains more than 100000 file entries.")
                }
                val roots = entries.filter { '/' in it }.map { it.substringBefore('/') }.distinct()
                val reserved = setOf("assets", "content", "patches", "sprites", "sounds", "music", "bundles", "meta-inf")
                val root = roots.singleOrNull()?.takeIf { candidate ->
                    entries.all { it.startsWith("$candidate/") } && candidate.lowercase(Locale.ROOT) !in reserved
                }
                return JarProvenanceIndex(entries.sorted(), root)
            }
        }
    }

    private val allowedParserNames = mapOf(
        "item" to setOf("Item"),
        "liquid" to setOf("Liquid", "CellLiquid"),
        "status" to setOf("StatusEffect"),
    )
    private val boolSpec = FieldSpec(setOf("boolean"))
    private val floatSpec = FieldSpec(setOf("number"), setOf("float"))
    private val intSpec = FieldSpec(setOf("number"), setOf("int"))
    private val colorSpec = FieldSpec(setOf("color"))
    private val effectSpec = FieldSpec(setOf("staticRef", "opaque"))
    private fun contentRefSpec(type: String) = FieldSpec(setOf("contentRef"), contentReferenceType = type)
    private fun contentRefArraySpec(type: String) = FieldSpec(
        setOf("array"),
        elementSpec = contentRefSpec(type),
    )
    private val itemFieldSpecs = buildMap {
        put("color", colorSpec)
        listOf("explosiveness", "flammability", "radioactivity", "charge", "cost", "healthScaling", "frameTime")
            .forEach { put(it, floatSpec) }
        listOf("hardness", "frames", "transitionFrames").forEach { put(it, intSpec) }
        listOf("lowPriority", "buildable", "hidden").forEach { put(it, boolSpec) }
    }
    private val liquidFieldSpecs = buildMap {
        listOf("gas", "blockReactive", "coolant", "moveThroughBlocks", "incinerable", "capPuddles", "hidden")
            .forEach { put(it, boolSpec) }
        listOf("color", "gasColor", "barColor", "lightColor").forEach { put(it, colorSpec) }
        listOf("flammability", "temperature", "heatCapacity", "viscosity", "explosiveness", "particleSpacing", "boilPoint")
            .forEach { put(it, floatSpec) }
        put("effect", contentRefSpec("status"))
        put("particleEffect", effectSpec)
        put("vaporEffect", effectSpec)
        put("canStayOn", contentRefArraySpec("liquid"))
    }
    private val cellLiquidFieldSpecs = buildMap {
        listOf("colorFrom", "colorTo").forEach { put(it, colorSpec) }
        put("cells", intSpec)
        put("spreadTarget", contentRefSpec("liquid"))
        listOf("maxSpread", "spreadConversion", "spreadDamage", "removeScaling").forEach { put(it, floatSpec) }
    }
    private val statusFieldSpecs = buildMap {
        listOf(
            "damageMultiplier", "healthMultiplier", "speedMultiplier", "reloadMultiplier", "buildSpeedMultiplier",
            "dragMultiplier", "transitionDamage", "damage", "intervalDamageTime", "intervalDamage", "effectChance",
        ).forEach { put(it, floatSpec) }
        listOf(
            "disarm", "intervalDamagePierce", "parentizeEffect", "permanent", "reactive", "dynamic", "show",
            "applyExtend", "parentizeApplyEffect", "outline",
        ).forEach { put(it, boolSpec) }
        listOf("color", "applyColor").forEach { put(it, colorSpec) }
        listOf("effect", "applyEffect").forEach { put(it, effectSpec) }
        put("affinities", contentRefArraySpec("status"))
        put("opposites", contentRefArraySpec("status"))
    }

    private val COLOR = Regex("(?i)^[0-9a-f]{8}$")
    private val SAFE_PARSER_NAME = Regex("^[A-Za-z_$][A-Za-z0-9_$]*$")
}
